FROM node:22-alpine AS base
RUN apk update && apk add --no-cache openssl
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY shared/logger/package.json ./shared/logger/
COPY shared/email/package.json ./shared/email/
COPY services/auth/package.json ./services/auth/
COPY services/users/package.json ./services/users/
COPY services/service-orders/package.json ./services/service-orders/
COPY prisma ./prisma

RUN pnpm install --frozen-lockfile
RUN pnpm exec prisma generate --schema=prisma/schema.prisma

FROM base AS auth-build
FROM base AS users-build
FROM base AS service-orders-build
